abstract_start_words :
 - "abstract"
 - "abstract of thesis"

abstract_stop_words :
 - "table of contents"
 - "acknowledgments"

title_stop_words :
 - "presented to"
 - "thesis by"
 - "thesis adviser"

city/state : "Quezon City"
